/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrganisationsRouteImport } from './routes/_app/organisations'
import { Route as AppObservablesRouteImport } from './routes/_app/observables'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app/knowledge-base'
import { Route as AppFunctionsRouteImport } from './routes/_app/functions'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'
import { Route as AppConnectorJobsRouteImport } from './routes/_app/connector-jobs'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppCaseTemplatesIndexRouteImport } from './routes/_app/case-templates/index'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings.$section'
import { Route as AppKnowledgeBasePageIdRouteImport } from './routes/_app/knowledge-base/$pageId'
import { Route as AppCasesCreateRouteImport } from './routes/_app/cases/create'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases/$caseId'
import { Route as AppCaseTemplatesTemplateIdRouteImport } from './routes/_app/case-templates/$templateId'
import { Route as AppCasesCaseIdIndexRouteImport } from './routes/_app/cases/$caseId/index'
import { Route as AppCasesCaseIdTabRouteImport } from './routes/_app/cases/$caseId/$tab'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppObservablesRoute = AppObservablesRouteImport.update({
  id: '/observables',
  path: '/observables',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppFunctionsRoute = AppFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorJobsRoute = AppConnectorJobsRouteImport.update({
  id: '/connector-jobs',
  path: '/connector-jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseTemplatesIndexRoute = AppCaseTemplatesIndexRouteImport.update({
  id: '/case-templates/',
  path: '/case-templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppKnowledgeBasePageIdRoute = AppKnowledgeBasePageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AppKnowledgeBaseRoute,
} as any)
const AppCasesCreateRoute = AppCasesCreateRouteImport.update({
  id: '/cases/create',
  path: '/cases/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseTemplatesTemplateIdRoute =
  AppCaseTemplatesTemplateIdRouteImport.update({
    id: '/case-templates/$templateId',
    path: '/case-templates/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCasesCaseIdIndexRoute = AppCasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)
const AppCasesCaseIdTabRoute = AppCasesCaseIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/connector-jobs': typeof AppConnectorJobsRoute
  '/connectors': typeof AppConnectorsRoute
  '/functions': typeof AppFunctionsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/observables': typeof AppObservablesRoute
  '/organisations': typeof AppOrganisationsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/cases/create': typeof AppCasesCreateRoute
  '/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/case-templates/': typeof AppCaseTemplatesIndexRoute
  '/cases/': typeof AppCasesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/connector-jobs': typeof AppConnectorJobsRoute
  '/connectors': typeof AppConnectorsRoute
  '/functions': typeof AppFunctionsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/observables': typeof AppObservablesRoute
  '/organisations': typeof AppOrganisationsRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/cases/create': typeof AppCasesCreateRoute
  '/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/case-templates': typeof AppCaseTemplatesIndexRoute
  '/cases': typeof AppCasesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/cases/$caseId': typeof AppCasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/connector-jobs': typeof AppConnectorJobsRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/functions': typeof AppFunctionsRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/_app/observables': typeof AppObservablesRoute
  '/_app/organisations': typeof AppOrganisationsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/_app/cases/create': typeof AppCasesCreateRoute
  '/_app/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/case-templates/': typeof AppCaseTemplatesIndexRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/_app/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/connector-jobs'
    | '/connectors'
    | '/functions'
    | '/knowledge-base'
    | '/observables'
    | '/organisations'
    | '/settings'
    | '/tasks'
    | '/case-templates/$templateId'
    | '/cases/$caseId'
    | '/cases/create'
    | '/knowledge-base/$pageId'
    | '/settings/$section'
    | '/case-templates/'
    | '/cases/'
    | '/settings/'
    | '/cases/$caseId/$tab'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alerts'
    | '/connector-jobs'
    | '/connectors'
    | '/functions'
    | '/knowledge-base'
    | '/observables'
    | '/organisations'
    | '/tasks'
    | '/'
    | '/case-templates/$templateId'
    | '/cases/create'
    | '/knowledge-base/$pageId'
    | '/settings/$section'
    | '/case-templates'
    | '/cases'
    | '/settings'
    | '/cases/$caseId/$tab'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/connector-jobs'
    | '/_app/connectors'
    | '/_app/functions'
    | '/_app/knowledge-base'
    | '/_app/observables'
    | '/_app/organisations'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/case-templates/$templateId'
    | '/_app/cases/$caseId'
    | '/_app/cases/create'
    | '/_app/knowledge-base/$pageId'
    | '/_app/settings/$section'
    | '/_app/case-templates/'
    | '/_app/cases/'
    | '/_app/settings/'
    | '/_app/cases/$caseId/$tab'
    | '/_app/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisations': {
      id: '/_app/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/observables': {
      id: '/_app/observables'
      path: '/observables'
      fullPath: '/observables'
      preLoaderRoute: typeof AppObservablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functions': {
      id: '/_app/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof AppFunctionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connector-jobs': {
      id: '/_app/connector-jobs'
      path: '/connector-jobs'
      fullPath: '/connector-jobs'
      preLoaderRoute: typeof AppConnectorJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-templates/': {
      id: '/_app/case-templates/'
      path: '/case-templates'
      fullPath: '/case-templates/'
      preLoaderRoute: typeof AppCaseTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/knowledge-base/$pageId': {
      id: '/_app/knowledge-base/$pageId'
      path: '/$pageId'
      fullPath: '/knowledge-base/$pageId'
      preLoaderRoute: typeof AppKnowledgeBasePageIdRouteImport
      parentRoute: typeof AppKnowledgeBaseRoute
    }
    '/_app/cases/create': {
      id: '/_app/cases/create'
      path: '/cases/create'
      fullPath: '/cases/create'
      preLoaderRoute: typeof AppCasesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-templates/$templateId': {
      id: '/_app/case-templates/$templateId'
      path: '/case-templates/$templateId'
      fullPath: '/case-templates/$templateId'
      preLoaderRoute: typeof AppCaseTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId/': {
      id: '/_app/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof AppCasesCaseIdIndexRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
    '/_app/cases/$caseId/$tab': {
      id: '/_app/cases/$caseId/$tab'
      path: '/$tab'
      fullPath: '/cases/$caseId/$tab'
      preLoaderRoute: typeof AppCasesCaseIdTabRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
  }
}

interface AppKnowledgeBaseRouteChildren {
  AppKnowledgeBasePageIdRoute: typeof AppKnowledgeBasePageIdRoute
}

const AppKnowledgeBaseRouteChildren: AppKnowledgeBaseRouteChildren = {
  AppKnowledgeBasePageIdRoute: AppKnowledgeBasePageIdRoute,
}

const AppKnowledgeBaseRouteWithChildren =
  AppKnowledgeBaseRoute._addFileChildren(AppKnowledgeBaseRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppCasesCaseIdRouteChildren {
  AppCasesCaseIdTabRoute: typeof AppCasesCaseIdTabRoute
  AppCasesCaseIdIndexRoute: typeof AppCasesCaseIdIndexRoute
}

const AppCasesCaseIdRouteChildren: AppCasesCaseIdRouteChildren = {
  AppCasesCaseIdTabRoute: AppCasesCaseIdTabRoute,
  AppCasesCaseIdIndexRoute: AppCasesCaseIdIndexRoute,
}

const AppCasesCaseIdRouteWithChildren = AppCasesCaseIdRoute._addFileChildren(
  AppCasesCaseIdRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppConnectorJobsRoute: typeof AppConnectorJobsRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppFunctionsRoute: typeof AppFunctionsRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRouteWithChildren
  AppObservablesRoute: typeof AppObservablesRoute
  AppOrganisationsRoute: typeof AppOrganisationsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCaseTemplatesTemplateIdRoute: typeof AppCaseTemplatesTemplateIdRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRouteWithChildren
  AppCasesCreateRoute: typeof AppCasesCreateRoute
  AppCaseTemplatesIndexRoute: typeof AppCaseTemplatesIndexRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppConnectorJobsRoute: AppConnectorJobsRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppFunctionsRoute: AppFunctionsRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRouteWithChildren,
  AppObservablesRoute: AppObservablesRoute,
  AppOrganisationsRoute: AppOrganisationsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCaseTemplatesTemplateIdRoute: AppCaseTemplatesTemplateIdRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRouteWithChildren,
  AppCasesCreateRoute: AppCasesCreateRoute,
  AppCaseTemplatesIndexRoute: AppCaseTemplatesIndexRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
