/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppPluginsRouteImport } from './routes/_app/plugins'
import { Route as AppPluginRunsRouteImport } from './routes/_app/plugin-runs'
import { Route as AppPluginRunnersRouteImport } from './routes/_app/plugin-runners'
import { Route as AppOrganisationsRouteImport } from './routes/_app/organisations'
import { Route as AppObservablesRouteImport } from './routes/_app/observables'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app/knowledge-base'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppAttackMatrixRouteImport } from './routes/_app/attack-matrix'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppCaseTemplatesIndexRouteImport } from './routes/_app/case-templates/index'
import { Route as AppAlertsIndexRouteImport } from './routes/_app/alerts.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account.index'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings.$section'
import { Route as AppKnowledgeBasePageIdRouteImport } from './routes/_app/knowledge-base/$pageId'
import { Route as AppCasesCreateRouteImport } from './routes/_app/cases/create'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases/$caseId'
import { Route as AppCaseTemplatesTemplateIdRouteImport } from './routes/_app/case-templates/$templateId'
import { Route as AppAlertsAlertIdRouteImport } from './routes/_app/alerts.$alertId'
import { Route as AppAdminSectionRouteImport } from './routes/_app/admin.$section'
import { Route as AppAccountSectionRouteImport } from './routes/_app/account.$section'
import { Route as AppCasesCaseIdIndexRouteImport } from './routes/_app/cases/$caseId/index'
import { Route as AppCasesCaseIdTabRouteImport } from './routes/_app/cases/$caseId/$tab'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsRoute = AppPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginRunsRoute = AppPluginRunsRouteImport.update({
  id: '/plugin-runs',
  path: '/plugin-runs',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginRunnersRoute = AppPluginRunnersRouteImport.update({
  id: '/plugin-runners',
  path: '/plugin-runners',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppObservablesRoute = AppObservablesRouteImport.update({
  id: '/observables',
  path: '/observables',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackMatrixRoute = AppAttackMatrixRouteImport.update({
  id: '/attack-matrix',
  path: '/attack-matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseTemplatesIndexRoute = AppCaseTemplatesIndexRouteImport.update({
  id: '/case-templates/',
  path: '/case-templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlertsRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppKnowledgeBasePageIdRoute = AppKnowledgeBasePageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AppKnowledgeBaseRoute,
} as any)
const AppCasesCreateRoute = AppCasesCreateRouteImport.update({
  id: '/cases/create',
  path: '/cases/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseTemplatesTemplateIdRoute =
  AppCaseTemplatesTemplateIdRouteImport.update({
    id: '/case-templates/$templateId',
    path: '/case-templates/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAlertsAlertIdRoute = AppAlertsAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => AppAlertsRoute,
} as any)
const AppAdminSectionRoute = AppAdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAccountSectionRoute = AppAccountSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppCasesCaseIdIndexRoute = AppCasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)
const AppCasesCaseIdTabRoute = AppCasesCaseIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AppAccountRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/alerts': typeof AppAlertsRouteWithChildren
  '/attack-matrix': typeof AppAttackMatrixRoute
  '/dashboards': typeof AppDashboardsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/observables': typeof AppObservablesRoute
  '/organisations': typeof AppOrganisationsRoute
  '/plugin-runners': typeof AppPluginRunnersRoute
  '/plugin-runs': typeof AppPluginRunsRoute
  '/plugins': typeof AppPluginsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/d/$token': typeof DTokenRoute
  '/account/$section': typeof AppAccountSectionRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/cases/create': typeof AppCasesCreateRoute
  '/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/account/': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/alerts/': typeof AppAlertsIndexRoute
  '/case-templates/': typeof AppCaseTemplatesIndexRoute
  '/cases/': typeof AppCasesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/attack-matrix': typeof AppAttackMatrixRoute
  '/dashboards': typeof AppDashboardsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/observables': typeof AppObservablesRoute
  '/organisations': typeof AppOrganisationsRoute
  '/plugin-runners': typeof AppPluginRunnersRoute
  '/plugin-runs': typeof AppPluginRunsRoute
  '/plugins': typeof AppPluginsRoute
  '/search': typeof AppSearchRoute
  '/tasks': typeof AppTasksRoute
  '/d/$token': typeof DTokenRoute
  '/': typeof AppIndexRoute
  '/account/$section': typeof AppAccountSectionRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/cases/create': typeof AppCasesCreateRoute
  '/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/case-templates': typeof AppCaseTemplatesIndexRoute
  '/cases': typeof AppCasesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/cases/$caseId': typeof AppCasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/alerts': typeof AppAlertsRouteWithChildren
  '/_app/attack-matrix': typeof AppAttackMatrixRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/_app/observables': typeof AppObservablesRoute
  '/_app/organisations': typeof AppOrganisationsRoute
  '/_app/plugin-runners': typeof AppPluginRunnersRoute
  '/_app/plugin-runs': typeof AppPluginRunsRoute
  '/_app/plugins': typeof AppPluginsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/d/$token': typeof DTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/$section': typeof AppAccountSectionRoute
  '/_app/admin/$section': typeof AppAdminSectionRoute
  '/_app/alerts/$alertId': typeof AppAlertsAlertIdRoute
  '/_app/case-templates/$templateId': typeof AppCaseTemplatesTemplateIdRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/_app/cases/create': typeof AppCasesCreateRoute
  '/_app/knowledge-base/$pageId': typeof AppKnowledgeBasePageIdRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/alerts/': typeof AppAlertsIndexRoute
  '/_app/case-templates/': typeof AppCaseTemplatesIndexRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/cases/$caseId/$tab': typeof AppCasesCaseIdTabRoute
  '/_app/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/alerts'
    | '/attack-matrix'
    | '/dashboards'
    | '/knowledge-base'
    | '/observables'
    | '/organisations'
    | '/plugin-runners'
    | '/plugin-runs'
    | '/plugins'
    | '/search'
    | '/settings'
    | '/tasks'
    | '/d/$token'
    | '/account/$section'
    | '/admin/$section'
    | '/alerts/$alertId'
    | '/case-templates/$templateId'
    | '/cases/$caseId'
    | '/cases/create'
    | '/knowledge-base/$pageId'
    | '/settings/$section'
    | '/account/'
    | '/admin/'
    | '/alerts/'
    | '/case-templates/'
    | '/cases/'
    | '/settings/'
    | '/cases/$caseId/$tab'
    | '/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/attack-matrix'
    | '/dashboards'
    | '/knowledge-base'
    | '/observables'
    | '/organisations'
    | '/plugin-runners'
    | '/plugin-runs'
    | '/plugins'
    | '/search'
    | '/tasks'
    | '/d/$token'
    | '/'
    | '/account/$section'
    | '/admin/$section'
    | '/alerts/$alertId'
    | '/case-templates/$templateId'
    | '/cases/create'
    | '/knowledge-base/$pageId'
    | '/settings/$section'
    | '/account'
    | '/admin'
    | '/alerts'
    | '/case-templates'
    | '/cases'
    | '/settings'
    | '/cases/$caseId/$tab'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/attack-matrix'
    | '/_app/dashboards'
    | '/_app/knowledge-base'
    | '/_app/observables'
    | '/_app/organisations'
    | '/_app/plugin-runners'
    | '/_app/plugin-runs'
    | '/_app/plugins'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/tasks'
    | '/d/$token'
    | '/_app/'
    | '/_app/account/$section'
    | '/_app/admin/$section'
    | '/_app/alerts/$alertId'
    | '/_app/case-templates/$templateId'
    | '/_app/cases/$caseId'
    | '/_app/cases/create'
    | '/_app/knowledge-base/$pageId'
    | '/_app/settings/$section'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/alerts/'
    | '/_app/case-templates/'
    | '/_app/cases/'
    | '/_app/settings/'
    | '/_app/cases/$caseId/$tab'
    | '/_app/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DTokenRoute: typeof DTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins': {
      id: '/_app/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AppPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugin-runs': {
      id: '/_app/plugin-runs'
      path: '/plugin-runs'
      fullPath: '/plugin-runs'
      preLoaderRoute: typeof AppPluginRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugin-runners': {
      id: '/_app/plugin-runners'
      path: '/plugin-runners'
      fullPath: '/plugin-runners'
      preLoaderRoute: typeof AppPluginRunnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisations': {
      id: '/_app/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/observables': {
      id: '/_app/observables'
      path: '/observables'
      fullPath: '/observables'
      preLoaderRoute: typeof AppObservablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-matrix': {
      id: '/_app/attack-matrix'
      path: '/attack-matrix'
      fullPath: '/attack-matrix'
      preLoaderRoute: typeof AppAttackMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-templates/': {
      id: '/_app/case-templates/'
      path: '/case-templates'
      fullPath: '/case-templates/'
      preLoaderRoute: typeof AppCaseTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/': {
      id: '/_app/alerts/'
      path: '/'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppAlertsRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/knowledge-base/$pageId': {
      id: '/_app/knowledge-base/$pageId'
      path: '/$pageId'
      fullPath: '/knowledge-base/$pageId'
      preLoaderRoute: typeof AppKnowledgeBasePageIdRouteImport
      parentRoute: typeof AppKnowledgeBaseRoute
    }
    '/_app/cases/create': {
      id: '/_app/cases/create'
      path: '/cases/create'
      fullPath: '/cases/create'
      preLoaderRoute: typeof AppCasesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-templates/$templateId': {
      id: '/_app/case-templates/$templateId'
      path: '/case-templates/$templateId'
      fullPath: '/case-templates/$templateId'
      preLoaderRoute: typeof AppCaseTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/$alertId': {
      id: '/_app/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AppAlertsAlertIdRouteImport
      parentRoute: typeof AppAlertsRoute
    }
    '/_app/admin/$section': {
      id: '/_app/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AppAdminSectionRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/account/$section': {
      id: '/_app/account/$section'
      path: '/$section'
      fullPath: '/account/$section'
      preLoaderRoute: typeof AppAccountSectionRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/cases/$caseId/': {
      id: '/_app/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof AppCasesCaseIdIndexRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
    '/_app/cases/$caseId/$tab': {
      id: '/_app/cases/$caseId/$tab'
      path: '/$tab'
      fullPath: '/cases/$caseId/$tab'
      preLoaderRoute: typeof AppCasesCaseIdTabRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountSectionRoute: typeof AppAccountSectionRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountSectionRoute: AppAccountSectionRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminSectionRoute: typeof AppAdminSectionRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminSectionRoute: AppAdminSectionRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAlertsRouteChildren {
  AppAlertsAlertIdRoute: typeof AppAlertsAlertIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
}

const AppAlertsRouteChildren: AppAlertsRouteChildren = {
  AppAlertsAlertIdRoute: AppAlertsAlertIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
}

const AppAlertsRouteWithChildren = AppAlertsRoute._addFileChildren(
  AppAlertsRouteChildren,
)

interface AppKnowledgeBaseRouteChildren {
  AppKnowledgeBasePageIdRoute: typeof AppKnowledgeBasePageIdRoute
}

const AppKnowledgeBaseRouteChildren: AppKnowledgeBaseRouteChildren = {
  AppKnowledgeBasePageIdRoute: AppKnowledgeBasePageIdRoute,
}

const AppKnowledgeBaseRouteWithChildren =
  AppKnowledgeBaseRoute._addFileChildren(AppKnowledgeBaseRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppCasesCaseIdRouteChildren {
  AppCasesCaseIdTabRoute: typeof AppCasesCaseIdTabRoute
  AppCasesCaseIdIndexRoute: typeof AppCasesCaseIdIndexRoute
}

const AppCasesCaseIdRouteChildren: AppCasesCaseIdRouteChildren = {
  AppCasesCaseIdTabRoute: AppCasesCaseIdTabRoute,
  AppCasesCaseIdIndexRoute: AppCasesCaseIdIndexRoute,
}

const AppCasesCaseIdRouteWithChildren = AppCasesCaseIdRoute._addFileChildren(
  AppCasesCaseIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAlertsRoute: typeof AppAlertsRouteWithChildren
  AppAttackMatrixRoute: typeof AppAttackMatrixRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRouteWithChildren
  AppObservablesRoute: typeof AppObservablesRoute
  AppOrganisationsRoute: typeof AppOrganisationsRoute
  AppPluginRunnersRoute: typeof AppPluginRunnersRoute
  AppPluginRunsRoute: typeof AppPluginRunsRoute
  AppPluginsRoute: typeof AppPluginsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCaseTemplatesTemplateIdRoute: typeof AppCaseTemplatesTemplateIdRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRouteWithChildren
  AppCasesCreateRoute: typeof AppCasesCreateRoute
  AppCaseTemplatesIndexRoute: typeof AppCaseTemplatesIndexRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAlertsRoute: AppAlertsRouteWithChildren,
  AppAttackMatrixRoute: AppAttackMatrixRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRouteWithChildren,
  AppObservablesRoute: AppObservablesRoute,
  AppOrganisationsRoute: AppOrganisationsRoute,
  AppPluginRunnersRoute: AppPluginRunnersRoute,
  AppPluginRunsRoute: AppPluginRunsRoute,
  AppPluginsRoute: AppPluginsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCaseTemplatesTemplateIdRoute: AppCaseTemplatesTemplateIdRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRouteWithChildren,
  AppCasesCreateRoute: AppCasesCreateRoute,
  AppCaseTemplatesIndexRoute: AppCaseTemplatesIndexRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DTokenRoute: DTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
